export const GET_ALL_NAMES = "GET_ALL_NAMES"
export const GET_IT_NAMES = "GET_IT_NAMES"
export const GET_MANUFACTURE_NAMES = "GET_MANUFACTURE_NAMES"
export const GET_SERVICES_NAMES = "GET_SERVICES_NAMES"